"""inbox tables

Revision ID: 0002_inbox
Revises: 0001_initial
Create Date: 2026-05-01 01:57:33.474727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_inbox'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buckets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buckets_user_id'), 'buckets', ['user_id'], unique=False)
    op.create_table('inbox_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gmail_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('bucket_id', sa.String(length=36), nullable=True),
    sa.Column('recent_message_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_threads_gmail_id'), 'inbox_threads', ['gmail_id'], unique=False)
    op.create_index(op.f('ix_inbox_threads_user_id'), 'inbox_threads', ['user_id'], unique=False)
    op.create_table('inbox_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gmail_id', sa.String(length=64), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=64), nullable=False),
    sa.Column('gmail_internal_date', sa.BigInteger(), nullable=False),
    sa.Column('gmail_history_id', sa.String(length=64), nullable=False),
    sa.Column('to_addr', sa.Text(), nullable=True),
    sa.Column('from_addr', sa.Text(), nullable=True),
    sa.Column('body_preview', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['inbox_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_messages_gmail_internal_date'), 'inbox_messages', ['gmail_internal_date'], unique=False)
    op.create_index(op.f('ix_inbox_messages_thread_id'), 'inbox_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_inbox_messages_user_id'), 'inbox_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Seed default buckets (user_id=None means shared across all users).
    op.bulk_insert(
        sa.table(
            "buckets",
            sa.column("id", sa.String),
            sa.column("user_id", sa.String),
            sa.column("name", sa.String),
            sa.column("criteria", sa.Text),
        ),
        [
            {"id": "default-important", "user_id": None, "name": "Important", "criteria": "needs response soon or affects me directly"},
            {"id": "default-can-wait", "user_id": None, "name": "Can wait", "criteria": "can be handled later, not urgent"},
            {"id": "default-auto-archive", "user_id": None, "name": "Auto-archive", "criteria": "automated notifications i don't act on"},
            {"id": "default-newsletter", "user_id": None, "name": "Newsletter", "criteria": "marketing or content subscriptions"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inbox_messages_user_id'), table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_thread_id'), table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_gmail_internal_date'), table_name='inbox_messages')
    op.drop_table('inbox_messages')
    op.drop_index(op.f('ix_inbox_threads_user_id'), table_name='inbox_threads')
    op.drop_index(op.f('ix_inbox_threads_gmail_id'), table_name='inbox_threads')
    op.drop_table('inbox_threads')
    op.drop_index(op.f('ix_buckets_user_id'), table_name='buckets')
    op.execute("DELETE FROM buckets WHERE user_id IS NULL")
    op.drop_table('buckets')
    # ### end Alembic commands ###
